spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  thymeleaf:
#    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
